### PR TITLE
Remove uses of ArgResultAliasAttr as it is not used, specced, or supported in VHLO

### PR DESCRIPTION
**Pull request by GleasonK**
Was looking at VHLO code coverage for serialization and realized the only unused attribute is ArgResultAliasAttr, because it was unsupported in VHLO legalizations. Speaking with @burmako it sounds like this attribute is unused and should not be in StableHLO/VHLO currently without an RFC first.

This is not an incompatibility since serialization would fail for programs that use this attribute currently.

Adding @sdasgup3 as reviewer as well for spec implications (should be none?)

### CODE REVIEW

**Comment by sdasgup3** [comment]
@GleasonK Just wanted to make sure that we will be having a separate Frontend contract ticket to remove the same from StableHLO per https://github.com/openxla/stablehlo/issues/1155.  Is that right?

**Comment by burmako** [comment]
Removing my assignment for now to get a review from @sdasgup3 first. I'll chime in afterwards.

**Review by sdasgup3 — APPROVED** [review]

**Review by burmako — APPROVED** [review]
I agree that this attribute can be removed without an RFC. To the best of my knowledge, it is unused (I added it to StableHLO in August when forking from MHLO, where it is currently unused as well).

Overall, the functionality implemented by this attribute is useful. Buffer donation is an important feature of the XLA compiler, so we should be able to represent it in StableHLO per the overall philosophy that we expose HLO semantics that existed at the time of forking MHLO into StableHLO. It's just that this has to be done in a deliberate way, and we have #740 to follow up on this.

Therefore, the overall idea behind this PR is LGTM. I have left a few minor comments - please feel free to merge after they are addressed.

**Comment by burmako** [comment]
@GleasonK Gentle ping. If I recall correctly, the proposed changes are fairly lightweight, so I think we should be fairly close to merging this after some minor follow-up work.

**Pull request merged**
