### PR TITLE
Add chlo legalize to stablehlo

### PR DESCRIPTION
**Pull request by linuxlonelyeagle**

### CODE REVIEW

**Comment by linuxlonelyeagle** [comment]
Regarding the [reason](https://github.com/openxla/stablehlo/issues/1895) for submitting this PR.

**Comment by GleasonK** [comment]
Hello!

Thanks again for the contributions 😄! I have lumped this PR and the canonicalizers one into a single RFC:
[[RFC] Adding StableHLO transformations for CHLO, Shape, Canonicalizations](https://groups.google.com/a/openxla.org/g/openxla-discuss/c/httnobiya7U)

The early feedback on this RFC is positive, so it seem plausible that we can proceed with these changes. If you have bandwidth, I think the proper / simpler solution would be to upstream the following CHLO files from IREE:
- CHLODecompositionPatterns.td
- LegalizeCHLO.cpp
- [Build targets for CHLO](https://github.com/openxla/iree/blob/406626bd90a8e8e76946215dbc04efe09eed24f5/compiler/plugins/input/StableHLO/stablehlo-iree/Conversion/BUILD.bazel#L49)
- tests in `Conversion/test/legalize_chlo_*.mlir`

If not, I'll do my best to prioritize upstreaming in the coming weeks!

**Comment by linuxlonelyeagle** [comment]
Thanks!I'll get it done.

**Comment by linuxlonelyeagle** [comment]
close by [1984](https://github.com/openxla/stablehlo/pull/1984).

**Pull request closed without merging**
