### PR TITLE
Tweak spec for special case when split_dim = concat_dim in all_to_all

### PR DESCRIPTION
**Pull request by mlevesquedion**
This was pointed out by Yuyou on the StableHLO Discord: https://discord.com/channels/999073994483433573/999074539138990131/1246199149905449060

### CODE REVIEW

**Review by sdasgup3 — APPROVED** [review]
Thanks for pointing this.

**Comment by mlevesquedion** [comment]
> Thanks for pointing this.

Thanks for the review!

I actually learned about this from someone on Discord! Thanks for the reminder, added proper credit to the PR description.

**Comment by Hatsunespica** [comment]
Hi! This is  Yuyou, and glad I did help on this project 0w0.
I am a PhD student at University of Utah, and working on compiler testing and verification so I am pretty sensitive to formalized constraints. 
Besides, I am really surprised SHLO has a so nice document for operations and their semantics as well as constraints, appreciate your effort.

**Comment by mlevesquedion** [comment]
> Hi! This is Yuyou, and glad I did help on this project 0w0. I am a PhD student at University of Utah, and working on compiler testing and verification so I am pretty sensitive to formalized constraints. Besides, I am really surprised SHLO has a so nice document for operations and their semantics as well as constraints, appreciate your effort.

Hi there!

Thank you for taking the time to look at the spec and for sharing a bit about yourself and your interests. I'm happy to hear that the StableHLO spec is useful to you! If you find more gaps in the spec (or any other area of the project), please feel free to open an issue or a pull request, or simply to ping us on Discord again.

Thanks :)

**Pull request merged**
