### PR TITLE
renaming interpreter.md

### PR DESCRIPTION
**Pull request by sdasgup3**
fixes https://github.com/openxla/stablehlo/issues/514

cc: @bhack

### CODE REVIEW

**Comment by bhack** [comment]
> The op-level eval as mentioned in (2)

What is `(2)`?

**Comment by sdasgup3** [comment]
>> What is (2)?
Thanks for the catch. Fixed it in the doc.

**Comment by bhack** [comment]
I will separate more 1 and 2 in two section but if the text is too short it is ok.

**Comment by sdasgup3** [comment]
Let us keep the bullets as is. 
Fixed the indentation.

**Pull request merged**
