### PR TITLE
Use DenseI64ArrayAttr for ops which already specialized the printing/parsing as DenseI64ArrayAttr

### PR DESCRIPTION
**Pull request by joker-eph**
Partially implement #1578

### CODE REVIEW

**Review by burmako — COMMENTED** [review]
Thanks for taking a stab at this! The DenseI64ArrayAttr API is definitely nicer. 

Let me take a bit of time to think about this PR: 1) plan for following up with implementing this change everywhere (so that we don't turn this into multiple breakages), 2) think about the implications for VHLO (the additional code in convertSpecial will grow considerably big once this is implemented everywhere).

**Comment by joker-eph** [comment]
> 2) think about the implications for VHLO (the additional code in convertSpecial will grow considerably big once this is implemented everywhere).

After this patch, there are 13 only DenseIntElementsAttr left in `StablehloOps.td` FYI

**Comment by joker-eph** [comment]
Weekly ping! There are already conflicts happening, I need to rebase and fix, but that'll be a constant thing...

**Comment by joker-eph** [comment]
> Weekly ping! There are already conflicts happening, I need to rebase and fix, but that'll be a constant thing...

Ping again @burmako ?

**Comment by burmako** [comment]
Hey! Apologies for not being super available. It was a short week last week because of holidays, so I'm a bit behind on this. Will follow up within the next 1-2 days.

**Comment by joker-eph** [comment]
Ping here?

**Comment by joker-eph** [comment]
New week, new ping! :)

**Comment by burmako** [comment]
Hi Mehdi! Thank you for your patience. I was out a lot in the last month (now I'm back), which brought me to this twilight zone where this thread definitely needs a reply but I'm too embarrassed because it has taken so long 😅

To catch up with the work that I was planning to do in July, I am planning to start with implementing the StableHLO => Linalg RFC ([current plan](https://docs.google.com/document/d/1ewi3KqKIQaJScMKIdTBgpm1Z7gxXJlTx0gH3GE7-WDE/edit#heading=h.5q14s9wkb7rr)), and then get to this PR. As promised, I'll rebase it and take it on personally to migrate everything, given that my delays in reviewing created a lot of extra work.

Does this plan work for you? I wanted to make sure that the rough timeline makes sense on your side.

**Comment by joker-eph** [comment]
@GleasonK maybe you can take this over? It's been waiting for 4 months, can we actually make it happen?

**Comment by mlevesquedion** [comment]
This PR was duplicated and merged in https://github.com/openxla/stablehlo/pull/1872, so it can now be closed. Thanks again, @joker-eph!

**Pull request closed without merging**
