### PR TITLE
GetDimensionSizeOp : make arguments quantized type

### PR DESCRIPTION
**Pull request by abhigunj**
~~DynamicBroadcastInDimOp:  is yet to be a part of spec.~~ (see comments)
GetDimensionSizeOp: will be changed to quantized types in spec. 
Back porting from the integration as file check tests were failing for both.

### CODE REVIEW

**Comment by sdasgup3** [comment]
`DynamicBroadcastInDimOp`: Feel free to update a description with that fact that there are internal tests written with per-axis support which we would like to maintain till the op makes its place to spec (at which point the decision can be revisted)

`GetDimensionSize`: Add the spec changes in the same PR stating that its semantics concerns only with the shape component of the type: The element-type could be anything.

**Review by GleasonK — COMMENTED** [review]
LGTM for GetDimSize. I can understand the use case here, and given that the output is not quantized, makes sense.

DynamicBroadcastInDim should match BroadcastInDim. Let's talk about the rationale for this a bit more before I approve. If this is to support a test case somewhere, perhaps we can remove that test case if it doesn't make sense?

What makes me hesitant is, what should the per-axis quantization be when the rank of the output doesn't match the rank of the input?

**Comment by GleasonK** [comment]
I also think that a ticket titled "Revisit quantization support for `dynamic_*` ops" is a fair outcome of this if we truly do want to defer this work until after speccing?

**Comment by sdasgup3** [comment]
>> What makes me hesitant is, what should the per-axis quantization be when the rank of the output doesn't match the rank of the input?

As the output shape is determined as by an operand for this op, it might not be possible to represent the output quantization type (unknown number of zero-point/scale pairs). Let's check if we can remove the test.

**Comment by abhigunj** [comment]
Thank you folks. Taking a look if we can remove the tests and keep DynamicBroadcastInDimOp without per-axis quantization for now.

@GleasonK  This PR needs to be merged before the start of this week integration to avoid reversing GetDimensionSize type change. I will update the PR soon regarding DynamicBroadcastInDimOp test removal and merge it.

**Comment by abhigunj** [comment]
Removed the DynamicBroadcastInDimOp changes form the PR; working on removing /updating tests from the g3. 

@GleasonK please flip the `HLO_Tensor` -> `HLO_TensorOrPerAxisQuantizedTensor` change during integration to avoid expected test failures. Sorry for the trouble.

**Review by GleasonK — APPROVED** [review]

**Pull request merged**
