### PR TITLE
[RFC] Add f8E4M3 and f8E3M4 types support

### PR DESCRIPTION
**Pull request by apivovarov**
### Summary
This is a proposal to add `Float8E4M3` and `Float8E3M4` floating point types to StableHLO.
Feedback welcome, see [RFC: Float8E4M3 and Float8E3M4](https://github.com/apivovarov/stablehlo/blob/rfc_f8E4M3_f8E3M4/rfcs/20240808-f8E4M3_f8E3M4.md) for more details.

### References and Links
- LLVM [PR-97179](https://github.com/llvm/llvm-project/pull/97179) [APFloat] Add support for f8E4M3 IEEE 754 type (Merged)
- LLVM [PR-97118](https://github.com/llvm/llvm-project/pull/97118) [MLIR] Add f8E4M3 IEEE 754 type (Merged)
- LLVM [PR-99698](https://github.com/llvm/llvm-project/pull/99698) [APFloat] Add support for f8E3M4 IEEE 754 type (Merged)
-  LLVM [PR-101230](https://github.com/llvm/llvm-project/pull/101230) [MLIR] Add f8E3M4 IEEE 754 type (Merged)
- [RFC: FP8 in StableHLO](https://github.com/openxla/stablehlo/blob/main/rfcs/20221031-fp8.md)
- [RFC: Float8E4M3FNUZ and Float8E5M2FNUZ](https://github.com/openxla/stablehlo/blob/main/rfcs/20230321-fp8_fnuz.md)
- StableHLO [PR-2482](https://github.com/openxla/stablehlo/pull/2482) Add f8E4M3 and f8E3M4 types support
- [Amazon EC2 Trn1 Instances](https://aws.amazon.com/ec2/instance-types/trn1/)
- ml_dtypes [PR-161](https://github.com/jax-ml/ml_dtypes/pull/161/) Add float8_e4m3 (Merged)
- ml_dtypes [PR-171](https://github.com/jax-ml/ml_dtypes/pull/171/) Add float8_e3m4 (Merged)
- XLA [PR-16585](https://github.com/openxla/xla/pull/16585) Add support for float8_e4m3

### CODE REVIEW

**Comment by GleasonK** [comment]
Signal boosted this to XLA devs, and generally positive feedback. Will give this a week comment period but general consensus is LGTM.

Summarizing some early feedback I've heard:
- Given that Amazon hardware supports these types, it makes sense to add to StableHLO.
- These new types are very well defined, underspecification tends to be the bigger risk with new type support (wouldn't want a correction to lead to an `fp8..._v2` type).
- Given the Trainium compilation pipeline (requires support in HLO/MHLO as well), adding type support elsewhere makes sense, and will be mostly boilerplate in XLA.

Also want to note that I'll continue socializing / signal boosting this, will report back additional feedback as I hear it / request feedback be left on the PR!

**Comment by apivovarov** [comment]
The RFC has been open for exactly two weeks. Should we keep it open longer, or is it ready to proceed?

You can find the implementation draft here: https://github.com/openxla/stablehlo/pull/2482

**Comment by GleasonK** [comment]
Hello! Yes sorry waiting on feedback from one more person from xla who said they wanted to look into this. Will follow up first thing tomorrow.

**Review by GleasonK — APPROVED** [review]

**Comment by GleasonK** [comment]
RFC LGTM. I wasn't able to get a hold of that last dev that wanted to chime in, but found a few proxy approvals internally who all agree that given that this is in IEEE and LLVM it should be good to go. Thanks for the contribution and apologies for the delay!

**Comment by apivovarov** [comment]
Great news! Thank you, Kevin, for you help and support!

**Pull request merged**
