### PR TITLE
Fix build error on macOS

### PR DESCRIPTION
**Pull request by anakinxc**
This is the same as #1293, but on newly added code.

### CODE REVIEW

**Review by rivertalk — APPROVED** [review]

**Comment by rivertalk** [comment]
Sorry, I clicked the approve button by mistake, please ack the reviewers to review it again.

**Comment by burmako** [comment]
Thank you for reporting a problem and coming up with a fix! Will merge momentarily.

**Comment by burmako** [comment]
@anakinxc Actually, now that some CI checks have finished, I noticed that there's a linter error. May I ask you to run `clang-format` on your PR?

**Review by burmako — APPROVED** [review]
LGTM once the formatting issues are fixed.

**Comment by anakinxc** [comment]
> LGTM once the formatting issues are fixed.

Done

**Pull request merged**
